In [8]:
import numpy as np
import pandas as pd

In [9]:
data = pd.read_excel('Business Analyst -ABC University.xlsx')

In [12]:
data_size = data.size
print(f"The dataset size is: {data_size}")

The dataset size is: 695288

In [17]:
rows, columns = data.shape
print(f"The dataset has {rows} rows and {columns} columns.")

The dataset has 31604 rows and 22 columns.

In [15]:
data.head(10)

,Name,Mobile,Lead Origin,Country,State,City,Instance,Instance Date,Campaign,Lead Stage,...,Mobile Verification Status,Registration Device,Course,Specialization,Campus,Last Lead Activity Date,Form Initiated,Paid Applications,Submitted Applications,Enrolment Status
0,Ram Yadav,9830******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/85/API,Untouched,...,No,NaN,B.Tech in Biomedical Engineering,Specialization Not Available,UG,2023-10-09 11:26:00,0,0,0,No
1,Anamika Bairagi,7439******,API,India,West Bengal,Barasat,Primary,2023-10-09,Meta/84/API,Disqualified,...,No,NaN,"BCA (Hons) in Banking, Financial Services and ...",Specialization Not Available,UG,2023-10-09 11:20:00,0,0,0,No
2,Puja Singh,7003******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/85/API,No Response,...,No,NaN,"MBA (Human Resource, Marketing, Finance)",Specialization Not Available,PG,2023-10-09 10:17:00,0,0,0,No
3,Jhuma Haldar,9831******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/88/API,Disqualified,...,No,NaN,M.A in Public Policy,Specialization Not Available,PG,2023-10-09 10:16:00,0,0,0,No
4,Rajan Kumar,9128******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/85/API,Disqualified,...,No,NaN,B.Com (H),Specialization Not Available,UG,2023-10-09 08:14:00,0,0,0,No
5,Deepshikha kamti,6291******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/85/API,Untouched,...,No,NaN,M.Com.,Specialization Not Available,PG,2023-10-09 07:05:00,0,0,0,No
6,Shivang soni,9674******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/85/API,Disqualified,...,No,NaN,MBA in Logistics and Supply Chain Management,Specialization Not Available,PG,2023-10-09 05:26:00,0,0,0,No
7,Kajol Rathi,9748******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/88/API,Disqualified,...,No,NaN,M.Com.,Specialization Not Available,PG,2023-10-09 03:39:00,0,0,0,No
8,Sayon chakraborty,9804******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/90_RV/API,No Response,...,No,NaN,"BCA (Hons) in Banking, Financial Services and ...",Specialization Not Available,UG,2023-10-09 02:35:00,0,0,0,No
9,Sk Zahira Khatun,9831******,API,India,West Bengal,Kolkata,Primary,2023-10-09,Meta/88/API,Disqualified,...,No,NaN,B.A (Hons.) Public Policy,Specialization Not Available,UG,2023-10-09 01:40:00,0,0,0,No

#### Data Cleaning for more accurate results

In [21]:
missing_values = data.isnull().sum()
print(missing_values)

Name                              0
Mobile                            0
Lead Origin                       0
Country                           0
State                             0
City                              0
Instance                          0
Instance Date                     0
Campaign                          0
Lead Stage                        0
Lead Status                       0
Email Verification Status         0
Mobile Verification Status        0
Registration Device           30912
Course                            0
Specialization                    0
Campus                            0
Last Lead Activity Date           0
Form Initiated                    0
Paid Applications                 0
Submitted Applications            0
Enrolment Status                  0
dtype: int64

##### After deleting the 30912 missing values we only left with the data having registration devices

In [26]:
regDevice_data = data.dropna()
regDevice_data.head()

,Name,Mobile,Lead Origin,Country,State,City,Instance,Instance Date,Campaign,Lead Stage,...,Mobile Verification Status,Registration Device,Course,Specialization,Campus,Last Lead Activity Date,Form Initiated,Paid Applications,Submitted Applications,Enrolment Status
279,Sneha Adhikary,6290******,Online,India,West Bengal,Kolkata,Primary,2023-10-04,Meta/aTextlink/Online,Qualified,...,Yes,Desktop,M.Sc in Environmental Science,School of Basic and Applied Sciences (SOBAS),PG,2023-10-04 22:00:00,1,0,0,No
344,Rahima khatun,7318******,Online,India,West Bengal,Jangipur,Primary,2023-10-03,Meta/Emailer/Online,Untouched,...,Yes,Mobile,Bengali,School of Liberal Arts and Culture Studies (SO...,PhD,2023-10-03 18:44:00,1,0,0,No
1810,ABHISHEK KUMAR,7352******,Online,India,Bihar,Patna,Primary,2023-09-12,Meta/Emailer/Online,Disqualified,...,Yes,Mobile,M.Sc. Tech (Statistics and Data Science),School of Basic and Applied Sciences (SOBAS),PG,2023-09-26 11:01:00,0,0,0,No
1826,Kankan Chakraborty,7584******,Online,India,West Bengal,Kolkata,Primary,2023-09-12,Meta/Emailer/Online,Disqualified,...,Yes,Mobile,M.Sc in Chemistry,School of Basic and Applied Sciences (SOBAS),PG,2023-09-26 11:01:00,0,0,0,No
1830,Srishti Kumari,9060******,Online,India,Bihar,Madhepura,Primary,2023-09-12,Meta/Emailer/Online,Disqualified,...,Yes,Mobile,M.Sc in Chemistry,School of Basic and Applied Sciences (SOBAS),PG,2023-09-26 11:01:00,1,0,0,No

##### Find Duplicates

In [37]:
duplicates = data.duplicated().sum()
print(f"There are {duplicates} Duplicate Values in the Dataset")

There are 0 Duplicate Values in the Dataset